#!/usr/bin/env python3
"""QuillyOS HTML Report Generator
Generates a static HTML report after each pipeline run.
Integrate into pipeline.py after run_pipeline() completes.

Usage:
  from html_report import generate_report
  generate_report(discovered_data, generated_post, status="dry-run")
"""
import json
from pathlib import Path
from datetime import datetime

HOME = Path("/data/data/com.termux/files/home")
REPORTS = HOME / "quillyos-nexus" / "reports"
REPORTS.mkdir(exist_ok=True)

TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>QuillyOS Report — {{timestamp}}</title>
<style>
body{{font-family:system-ui,-apple-system,sans-serif;max-width:800px;margin:0 auto;padding:20px;background:#0a0a0a;color:#e0e0e0}}
h1{{color:#00ff88;border-bottom:2px solid #00ff88;padding-bottom:10px}}
.section{{background:#1a1a1a;border-radius:8px;padding:16px;margin:16px 0}}
.section h2{{color:#ffaa00;margin-top:0}}
pre{{background:#0a0a0a;padding:12px;border-radius:6px;overflow-x:auto;font-size:13px}}
.tag{{display:inline-block;background:#00ff88;color:#000;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:bold;margin-right:6px}}
.status-live{{background:#ff4444}}
.status-dry{{background:#ffaa00}}
</style>
</head>
<body>
<h1>🚀 QuillyOS Pipeline Report</h1>
<p><span class="tag">{{status_class}}</span> <strong>{{timestamp}}</strong></p>

<div class="section">
<h2>🔍 Discovered Content</h2>
<pre>{{discovered_json}}</pre>
</div>

<div class="section">
<h2>📝 Generated Post</h2>
<pre>{{post_text}}</pre>
</div>

<div class="section">
<h2>📊 Metadata</h2>
<pre>Status: {{status}}
Report File: {{filename}}
Generated By: QuillyOS UGC Pipeline v0.1</pre>
</div>

</body>
</html>
"""

def generate_report(discovered, post, status="dry-run"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"report_{{datetime.now().strftime('%Y%m%d_%H%M%S')}}.html"
    fpath = REPORTS / filename

    status_class = "status-live" if status == "live" else "status-dry"
    status_label = "LIVE POST" if status == "live" else "DRY RUN"

    html = TEMPLATE.format(
        timestamp=timestamp,
        status_class=status_label,
        discovered_json=json.dumps(discovered, indent=2, default=str)[:2000],
        post_text=post,
        status=status.upper(),
        filename=filename
    )

    fpath.write_text(html)
    print(f"[+] HTML report: {{fpath}}")
    return str(fpath)

if __name__ == "__main__":
    # Demo
    demo_discovered = {{"tavily": [{{"title": "Demo", "url": "https://example.com"}}]}}
    demo_post = "Demo post content here. #tech #ai"
    generate_report(demo_discovered, demo_post, "dry-run")
